// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXOfjBAjnNhKUaERJPi2awfK2jnmNIekk',
    appId: '1:245561382640:web:0da1c47f55e97e25461435',
    messagingSenderId: '245561382640',
    projectId: 'reminders-aa9aa',
    authDomain: 'reminders-aa9aa.firebaseapp.com',
    storageBucket: 'reminders-aa9aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ3u-2AXo1eJscz0M5RiJ_RlFlG0tBRBs',
    appId: '1:245561382640:android:2d17fa52a62cfe42461435',
    messagingSenderId: '245561382640',
    projectId: 'reminders-aa9aa',
    storageBucket: 'reminders-aa9aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrHCvkk2sJgRHl-N9T9bTrnNbaOLnncE4',
    appId: '1:245561382640:ios:1c3eaf68b0f4d58f461435',
    messagingSenderId: '245561382640',
    projectId: 'reminders-aa9aa',
    storageBucket: 'reminders-aa9aa.appspot.com',
    iosBundleId: 'com.example.piaOrganizador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrHCvkk2sJgRHl-N9T9bTrnNbaOLnncE4',
    appId: '1:245561382640:ios:1c3eaf68b0f4d58f461435',
    messagingSenderId: '245561382640',
    projectId: 'reminders-aa9aa',
    storageBucket: 'reminders-aa9aa.appspot.com',
    iosBundleId: 'com.example.piaOrganizador',
  );
}
